default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres

development:
  <<: *default
  database: is-1_development

test:
  <<: *default
  database: is-1_test

production:
  <<: *default
  database: is-1_production
  username: is-1
  password: <%= ENV['IS-1_DATABASE_PASSWORD'] %>
